
name: Deploy Strapi to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install 

      - name: Build Strapi project
        run: npm run build


      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update your package list
            sudo apt-get update
            git clone https://github.com/haripriya2413/strapi-project.git
            cd strapi-project
            pm2 restart strapi || pm2 start npm --name "strapi-project" -- run start

            
            #cd /home/ubuntu/strapi-project
            #sudo npm install -g pm2
              cd /home/ubuntu/strapi-project
              git pull origin main
              npm install 
              npm run build
              pm2 restart strapi-project --update-env || pm2 start npm --name "strapi-project" -- run start

            #git pull origin main
            #npm install
            #npm run build
            #pm2 restart "strapi-project" || pm2 start npm --name "strapi-project" --run start
            #pm2 restart all || pm2 start npm --name "strapi-project" -- run start
